// First 20 data rows from enriched.xlsx, intentionally kept as a small UI fixture.
// Do not treat this as the complete catalog.
export type EnrichedProduct = {
  id: string
  row: number
  brand: string
  name: string
  url: string
  image: string
  price: number | null
  originalPrice: number | null
  cooling: string
  energy: string
  features: string
  warranty: string
  rating: string
  noise: string
  coverage: string
  compressorWarranty: string
}

export const enrichedProducts: EnrichedProduct[] = [
  {
    id: '362465',
    row: 1,
    brand: 'Panasonic',
    name: 'Máy lạnh Panasonic Inverter 2.5 HP CU/CS-PU24CKH-8D',
    url: 'https://www.dienmayxanh.com/may-lanh/panasonic-inverter-25-hp-cu-cs-pu24ckh-8d',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/362465/panasonic-inverter-25-hp-cu-cs-pu24ckh-8d-thumbksp-639162127486866503-600x600.jpg',
    price: 29490000,
    originalPrice: null,
    cooling: 'Powerful',
    energy: 'Inverter | ECO tích hợp A.I',
    features:
      'Nắp dàn lạnh có thể tháo rời, dễ dàng vệ sinh | Hẹn giờ bật, tắt máy | Điều khiển bằng điện thoại, có Wi-Fi | Hoạt động siêu êm Quiet | Sleep Mode | Chức năng khử ẩm | Dàn nóng phủ lớp BlueFin chống ăn mòn | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện',
    warranty: '1 năm',
    rating: '5 sao (Hiệu suất năng lượng 6.23)',
    noise: 'Dàn lạnh: 45/34/29 dB - Dàn nóng: 51 dB',
    coverage: 'Từ 30 - 40m² (từ 80 đến 120m³)',
    compressorWarranty: 'Máy nén 12 năm',
  },
  {
    id: '335837',
    row: 2,
    brand: 'Gree',
    name: 'Máy lạnh Gree Inverter 1 HP BD9CI',
    url: 'https://www.dienmayxanh.com/may-lanh/gree-inverter-1-hp-bd9ci',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/335837/gree-inverter-1-hp-bd9ci-thumb-639167010454195590-600x600.jpg',
    price: 9590000,
    originalPrice: 9990000,
    cooling: 'Turbo',
    energy: 'Real Inverter',
    features:
      'Hoạt động siêu êm Quiet | Chế độ tự làm sạch G-Clean | Chế độ Stand by 0.5W | Chức năng tự chẩn đoán lỗi | Có 7 cấp độ gió | Công nghệ BLACK FIN - tăng cường khả năng chống ăn mòn | 3 chế độ ngủ thông minh | Khóa trẻ em',
    warranty: '5 năm',
    rating: '3 sao (Hiệu suất năng lượng 4.55)',
    noise: 'Dàn lạnh: 38 dB - Dàn nóng: 49 dB',
    coverage: 'Dưới 15m² (từ 30 đến 45m³)',
    compressorWarranty: 'Máy nén 10 năm',
  },
  {
    id: '336040',
    row: 3,
    brand: 'Gree',
    name: 'Máy lạnh Gree Inverter 1.5 HP BD12CI',
    url: 'https://www.dienmayxanh.com/may-lanh/gree-inverter-1-5-hp-bd12ci',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/336040/gree-inverter-1-5-hp-bd12ci-thumb-639167011367319993-600x600.jpg',
    price: 11390000,
    originalPrice: 11690000,
    cooling: 'Turbo',
    energy: 'Real Inverter',
    features:
      'Hoạt động siêu êm Quiet | Chế độ tự làm sạch G-Clean | Chế độ Stand by 0.5W | Chức năng tự chẩn đoán lỗi | Có 7 cấp độ gió | Công nghệ BLACK FIN - tăng cường khả năng chống ăn mòn | 3 chế độ ngủ thông minh | Khóa trẻ em',
    warranty: '5 năm',
    rating: '3 sao (Hiệu suất năng lượng 4.39)',
    noise: 'Dàn lạnh: 37 dB - Dàn nóng: 50 dB',
    coverage: 'Từ 15 - 20m² (từ 40 đến 60m³)',
    compressorWarranty: 'Máy nén 10 năm',
  },
  {
    id: '336043',
    row: 4,
    brand: 'Gree',
    name: 'Máy lạnh Gree Inverter 2 HP BD18CI',
    url: 'https://www.dienmayxanh.com/may-lanh/gree-inverter-2-hp-bd18ci',
    image: 'https://cdn.tgdd.vn/2026/05/timerseo/336043.jpg',
    price: 17790000,
    originalPrice: 18090000,
    cooling: 'Turbo',
    energy: 'Real Inverter',
    features:
      'Hoạt động siêu êm Quiet | Chế độ tự làm sạch G-Clean | Chế độ Stand by 0.5W | Chức năng tự chẩn đoán lỗi | Có 7 cấp độ gió | Công nghệ BLACK FIN - tăng cường khả năng chống ăn mòn | 3 chế độ ngủ thông minh | Khóa trẻ em',
    warranty: '5 năm',
    rating: '4 sao (Hiệu suất năng lượng 4.94)',
    noise: 'Dàn lạnh: 46 dB - Dàn nóng: 53 dB',
    coverage: 'Từ 20 - 30m² (từ 60 đến 80m³)',
    compressorWarranty: 'Máy nén 10 năm',
  },
  {
    id: '320893',
    row: 5,
    brand: 'Midea',
    name: 'Máy lạnh Midea Inverter 1 HP MAFA-09CDN8',
    url: 'https://www.dienmayxanh.com/may-lanh/midea-inverter-1-hp-mafa-09cdn8',
    image: 'https://cdn.tgdd.vn/2026/07/timerseo/320893.png',
    price: 6190000,
    originalPrice: 8590000,
    cooling: 'Turbo',
    energy: 'Inverter | iEco',
    features:
      'Chế độ ngủ đêm Sleep cho người già, trẻ nhỏ | Hẹn giờ bật, tắt máy | Màn hình hiển thị nhiệt độ trên dàn lạnh | Chức năng bật tắt đèn hiển thị khi làm việc | Khóa remote điều khiển',
    warranty: '3 năm',
    rating: '4 sao (Hiệu suất năng lượng 5.06)',
    noise: 'Dàn lạnh: 33 dB - Dàn nóng: 54.5 dB',
    coverage: 'Dưới 15m² (từ 30 đến 45m³)',
    compressorWarranty: 'Máy nén 5 năm',
  },
  {
    id: '361686',
    row: 6,
    brand: 'Funiki',
    name: 'Máy lạnh Funiki Inverter 1 HP HPIC09TMU',
    url: 'https://www.dienmayxanh.com/may-lanh/funiki-inverter-1-hp-hpic09tmu',
    image: 'https://cdn.tgdd.vn/2026/05/timerseo/361686.png',
    price: 9500000,
    originalPrice: null,
    cooling: 'Turbo+',
    energy: 'Inverter | Eco',
    features:
      'Hẹn giờ bật, tắt máy | Màn hình hiển thị nhiệt độ trên dàn lạnh | Sleep Mode | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện | Chức năng tự làm sạch',
    warranty: '2 năm',
    rating: '5 sao (Hiệu suất năng lượng 6.01)',
    noise: 'Dàn lạnh: 37.5/30/27.5 dB - Dàn nóng: 53 dB',
    coverage: 'Dưới 15m² (từ 30 đến 45m³)',
    compressorWarranty: 'Máy nén 2 năm',
  },
  {
    id: '338854',
    row: 7,
    brand: 'LG',
    name: 'Máy lạnh âm trần LG Inverter 5 HP ZTNQ48GYLA0',
    url: 'https://www.dienmayxanh.com/may-lanh/am-tran-lg-inverter-5-hp-ztnq48gyla0',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/338854/am-tran-lg-inverter-5-hp-ztnq48gyla0-thumb-639112041509038397-600x600.jpg',
    price: 61090000,
    originalPrice: null,
    cooling: 'Có',
    energy: 'Smart Inverter',
    features:
      'Hẹn giờ tắt máy | Chức năng khử ẩm | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện',
    warranty: '2 năm',
    rating: 'Không',
    noise: 'Dàn lạnh: 44 dB - Dàn nóng: 55 dB',
    coverage: 'Từ 55 - 75m² (từ 165 đến 225m³)',
    compressorWarranty: 'Máy nén 2 năm',
  },
  {
    id: '338769',
    row: 8,
    brand: 'LG',
    name: 'Máy lạnh âm trần LG Inverter 4 HP ZTNQ36GYLA0',
    url: 'https://www.dienmayxanh.com/may-lanh/am-tran-lg-inverter-4-hp-ztnq36gyla0',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/338769/am-tran-lg-inverter-4-hp-ztnq36gyla0-thumb-639112041677737697-600x600.jpg',
    price: 58890000,
    originalPrice: null,
    cooling: 'Có',
    energy: 'Smart Inverter',
    features:
      'Hẹn giờ tắt máy | Chức năng khử ẩm | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện',
    warranty: '2 năm',
    rating: 'Không',
    noise: 'Dàn lạnh: 40 dB - Dàn nóng: 55 dB',
    coverage: 'Từ 40 - 60m² (từ 120 - 180m³)',
    compressorWarranty: 'Máy nén 2 năm',
  },
  {
    id: '327059',
    row: 9,
    brand: 'Aqua',
    name: 'Máy lạnh Aqua Inverter 1 HP AQA-RUV10SAW',
    url: 'https://www.dienmayxanh.com/may-lanh/aqua-inverter-1-hp-aqa-ruv10saw',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/327059/aqua-inverter-1-hp-aqa-ruv10saw-thumb1-639112082043701503-600x600.jpg',
    price: 14090000,
    originalPrice: null,
    cooling: 'Turbo',
    energy: 'Inverter | Cảm biến thông minh Eco',
    features:
      'Chức năng tự làm sạch dàn lạnh Self Clean | Hút ẩm thông minh Smart Dry | Kết nối IOT | Điều khiển bằng điện thoại, có Wi-Fi | Màn hình hiển thị nhiệt độ trên dàn lạnh | Sleep Mode | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện',
    warranty: '2 năm',
    rating: '5 sao (Hiệu suất năng lượng 6.75)',
    noise: 'Dàn lạnh: 32 dB - Dàn nóng: 52 dB',
    coverage: 'Dưới 15m² (từ 30 đến 45m³)',
    compressorWarranty: 'Máy nén 12 năm',
  },
  {
    id: '322606',
    row: 10,
    brand: 'LG',
    name: 'Máy lạnh LG Inverter 1.5 HP V13APIB',
    url: 'https://www.dienmayxanh.com/may-lanh/lg-inverter-1-5-hp-v13apib',
    image:
      'https://cdn.tgdd.vn/Products/Images/2002/322606/lg-inverter-1-5-hp-v13apib-040324-052912-550x160.jpg',
    price: 19390000,
    originalPrice: null,
    cooling: 'Jet Cool',
    energy: 'Dual Inverter | Energy Ctrl - Kiểm soát năng lượng chủ động 4 mức',
    features:
      'Hẹn giờ bật, tắt máy | Điều khiển bằng điện thoại, có Wi-Fi | Màn hình hiển thị nhiệt độ trên dàn lạnh | Thổi gió dễ chịu (cho trẻ em, người già) | Chế độ ngủ đêm tránh buốt | Công nghệ Gold-Fin chống ăn mòn | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện | Chức năng tự làm sạch',
    warranty: '2 năm',
    rating: '5 sao (Hiệu suất năng lượng 5.29)',
    noise: 'Dàn lạnh: 21 - 39 dB - Dàn nóng: 50 dB',
    coverage: 'Từ 15 - 20m² (từ 40 đến 60m³)',
    compressorWarranty: 'Máy nén 10 năm',
  },
  {
    id: '320851',
    row: 11,
    brand: 'Aqua',
    name: 'Máy lạnh AQUA Inverter 2 HP AQA-RV18QE',
    url: 'https://www.dienmayxanh.com/may-lanh/aqua-inverter-2-hp-aqa-rv18qe',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/320851/aqua-inverter-2-hp-aqa-rv18qe-thumb1-639112071837184652-600x600.jpg',
    price: 13990000,
    originalPrice: 15890000,
    cooling: 'Turbo',
    energy: 'Inverter | Cảm biến thông minh Eco',
    features:
      'Hút ẩm thông minh Smart Dry | Màn hình hiển thị nhiệt độ trên dàn lạnh | Sleep Mode | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện | Chức năng tự làm sạch',
    warranty: '2 năm',
    rating: '5 sao (Hiệu suất năng lượng 4.53)',
    noise: 'Dàn lạnh: 30 dB - Dàn nóng: 50 dB',
    coverage: 'Từ 20 - 30m² (từ 60 đến 80m³)',
    compressorWarranty: 'Máy nén 12 năm',
  },
  {
    id: '320750',
    row: 12,
    brand: 'Samsung',
    name: 'Máy lạnh tủ đứng Samsung Inverter 3 HP AC030BNPDKC/TC',
    url: 'https://www.dienmayxanh.com/may-lanh/tu-dung-samsung-inverter-3-hp-ac030bnpdkc-tc',
    image:
      'https://cdn.tgdd.vn/Products/Images/2002/320750/tu-dung-samsung-inverter-3-hp-ac030bnpdkc-tc-291223-103450-550x160.jpg',
    price: null,
    originalPrice: null,
    cooling: 'Fast Cooling',
    energy: 'Digital Inverter',
    features:
      'Kết nối Wifi SmartThings (cần gắn thêm phụ kiện) | Công nghệ cảm ứng điều khiển bề mặt',
    warranty: '2 năm',
    rating: 'Hãng không công bố',
    noise: '46/43/40 - 52 dB',
    coverage: 'Từ 35 - 50m²',
    compressorWarranty: 'Máy nén 5 năm',
  },
  {
    id: '309828',
    row: 13,
    brand: 'Samsung',
    name: 'Máy lạnh Samsung Inverter 1.5 HP AR12TYHQASINSV',
    url: 'https://www.dienmayxanh.com/may-lanh/samsung-inverter-1-hp-ar12tyhqasinsv',
    image:
      'https://cdn.tgdd.vn/Products/Images/2002/309828/samsung-inverter-1-hp-ar12tyhqasinsv-550x160.jpg',
    price: null,
    originalPrice: null,
    cooling: 'Fast Cool & Comfort Cool',
    energy: 'Digital Inverter Boost',
    features:
      'Chế độ ngủ ngon Good Sleep | Hẹn giờ bật, tắt máy | Màn hình hiển thị nhiệt độ trên dàn lạnh | Tự khởi động lại khi có điện',
    warranty: '2 năm',
    rating: '5 sao (Hiệu suất năng lượng 4.50 )',
    noise: '35 - 45/58 dB',
    coverage: 'Từ 15 - 20m² (từ 40 đến 60m³)',
    compressorWarranty: 'Máy nén 10 năm',
  },
  {
    id: '306964',
    row: 14,
    brand: 'Panasonic',
    name: 'Máy lạnh âm trần Panasonic Inverter 5 HP S-3448PU3HA/U-48PRH1H5',
    url: 'https://www.dienmayxanh.com/may-lanh/am-tran-panasonic-5-hp-s-3448pu3ha-u-48prh1h5',
    image:
      'https://cdn.tgdd.vn/Products/Images/2002/306964/product-306964-090523-120039-550x160.jpg',
    price: null,
    originalPrice: null,
    cooling: 'Turbo',
    energy: 'Inverter',
    features: 'Điều khiển từ xa thế hệ mới CONEX',
    warranty: '1 năm',
    rating: 'Không có',
    noise: '47/41 dB',
    coverage: 'Từ 55 - 75m² (từ 165 đến 225m³)',
    compressorWarranty: 'Máy nén 5 năm',
  },
  {
    id: '306963',
    row: 15,
    brand: 'Panasonic',
    name: 'Máy lạnh âm trần Panasonic Inverter 4 HP S-3448PU3HA/U-34PRH1H5',
    url: 'https://www.dienmayxanh.com/may-lanh/am-tran-panasonic-4-hp-s-3448pu3ha-u-34prh1h5',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/306963/am-tran-panasonic-4-hp-s-3448pu3ha-u-34prh1h5-thumb-01-639188878122704915-600x600.jpg',
    price: null,
    originalPrice: null,
    cooling: 'Turbo',
    energy: 'Inverter',
    features: 'Điều khiển từ xa thế hệ mới CONEX',
    warranty: '5 năm',
    rating: 'Không có',
    noise: '47/41 dB',
    coverage: 'Từ 40 - 60m² (từ 120 - 180m³)',
    compressorWarranty: 'Máy nén 5 năm',
  },
  {
    id: '306962',
    row: 16,
    brand: 'Panasonic',
    name: 'Máy lạnh âm trần Panasonic Inverter 2 HP S-1821PU3HA/U-21PRH1H5',
    url: 'https://www.dienmayxanh.com/may-lanh/am-tran-panasonic-inverter-2-hp-s-1821pu3ha-u-21prh1h5',
    image:
      'https://cdn.tgdd.vn/Products/Images/2002/306962/product-306962-090523-115345-550x160.jpg',
    price: null,
    originalPrice: null,
    cooling: 'Turbo',
    energy: 'Inverter',
    features: 'Điều khiển từ xa thế hệ mới CONEX',
    warranty: '5 năm',
    rating: 'Không có',
    noise: '42/35 dB',
    coverage: 'Từ 20 - 30m² (từ 60 đến 80m³)',
    compressorWarranty: 'Máy nén 5 năm',
  },
  {
    id: '306961',
    row: 17,
    brand: 'Panasonic',
    name: 'Máy lạnh âm trần Panasonic 2.5 HP S-2430PU3H/U-24PR1H5',
    url: 'https://www.dienmayxanh.com/may-lanh/am-tran-panasonic-25-hp-s-2430pu3h-u-24pr1h5',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/306961/am-tran-panasonic-25-hp-s-2430pu3h-u-24pr1h5-thumb-01-639185979468661536-600x600.jpg',
    price: 38290000,
    originalPrice: null,
    cooling: 'Turbo',
    energy: 'Inverter',
    features: 'Điều khiển từ xa thế hệ mới CONEX',
    warranty: '5 năm',
    rating: 'Không có',
    noise: '42/35 dB',
    coverage: 'Từ 30 - 40m² (từ 80 đến 120m³)',
    compressorWarranty: 'Máy nén 5 năm',
  },
  {
    id: '303861',
    row: 18,
    brand: 'Aqua',
    name: 'Máy lạnh Aqua Inverter 1 HP AQA-RUV10XAW',
    url: 'https://www.dienmayxanh.com/may-lanh/aqua-inverter-1-hp-aqa-ruv10xaw',
    image:
      'https://cdn.tgdd.vn/Products/Images/2002/303861/may-lanh-aqua-inverter-1-hp-aqa-ruv10xaw-050523-044128-550x160.jpg',
    price: null,
    originalPrice: null,
    cooling: 'Turbo',
    energy: 'Inverter | Eco',
    features:
      'Chức năng tự làm sạch dàn lạnh Self Clean | Điều khiển bằng điện thoại, có Wi-Fi | Màn hình hiển thị nhiệt độ trên dàn lạnh | Sleep Mode | Chức năng tự chẩn đoán lỗi | Tự khởi động lại khi có điện',
    warranty: '2 năm',
    rating: '5 sao (Hiệu suất năng lượng 5.43)',
    noise: '30 - 39 dB',
    coverage: 'Dưới 15m² (từ 30 đến 45m³)',
    compressorWarranty: 'Máy nén 10 năm',
  },
  {
    id: '299819',
    row: 19,
    brand: 'LG',
    name: 'Máy lạnh âm trần LG Inverter 3 HP ZTNQ30GNLE0',
    url: 'https://www.dienmayxanh.com/may-lanh/am-tran-lg-ztnq30gnle0',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/299819/am-tran-lg-ztnq30gnle0-thumb1-639112058552720548-600x600.jpg',
    price: 35000000,
    originalPrice: 42090000,
    cooling: 'Có',
    energy: 'Smart Inverter',
    features: '',
    warranty: '2 năm',
    rating: 'Không',
    noise: 'Dàn lạnh: 37 - 45 dB - Dàn nóng: 53 dB',
    coverage: 'Từ 35 - 40m² (từ 105 đến 120m³)',
    compressorWarranty: 'Máy nén 2 năm',
  },
  {
    id: '299816',
    row: 20,
    brand: 'LG',
    name: 'Máy lạnh tủ đứng LG Inverter 5 HP ZPNQ48LT3A0 (3 Pha)',
    url: 'https://www.dienmayxanh.com/may-lanh/tu-dung-lg-inverter-5-hp-zpnq48lt3a0-3-pha',
    image:
      'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/2002/299816/tu-dung-lg-inverter-5-hp-zpnq48lt3a0-3-pha-thumb1-639112055428438572-600x600.jpg',
    price: 60690000,
    originalPrice: null,
    cooling: 'Có',
    energy: 'Smart Inverter',
    features: '',
    warranty: '2 năm',
    rating: 'Không',
    noise: 'Dàn lạnh: 37 - 45 dB - Dàn nóng: 53 dB',
    coverage: 'Từ 60 - 70m² (từ 160 - 210m³)',
    compressorWarranty: 'Máy nén 2 năm',
  },
]
